version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: bc-api
    ports:
      - "8000:8000"
    networks: [mlnet]

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    container_name: bc-app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
    networks: [mlnet]

networks:
  mlnet:
    driver: bridge
